# Generated by Django 2.0.7 on 2018-08-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busmap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='bus_number',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='space',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
